name: Build exe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
        architecture: x86 

    - name: Install Dependencies
      run: |
        pip install nuitka

    - name: Build exe
      run: python -m nuitka --standalone --windows-disable-console --onefile --windows-icon-from-ico="./64x64.ico" --follow-imports --enable-plugin=tk-inter  --windows-uac-admin --windows-company-name="Mami" --windows-file-description="bedava Minecraft çalıştır beniiii" --windows-file-version="1.0.0" --windows-product-version="1.0.0" --trademarks="Anti-Trademark" --windows-product-name="Mami" --copyright="Copyleft 2024 Mami" "./mami.py"
    - name: Upload exe
      uses: actions/upload-artifact@v2
      with:
        name: mamiexe
        path: dist/
