name: Build exe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
        architecture: x86 

    - name: Install Dependencies
      run: |
        pip install pyinstaller
        pip install pywin32 

    - name: Build exe
      run: pyinstaller --onefile --noconsole mami.py

    - name: Upload exe
      uses: actions/upload-artifact@v2
      with:
        name: mamiexe
        path: dist/
